project:
  type: website
  output-dir: docs

website:
  title: "Arohit Talari"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/arohittalari
      - icon: github
        href: https://github.com/arohittalari

format:
  html:
    theme: cosmo
    css: styles.css
